import rand_select
print("################################################################################")
print("#                                    HANGMAN                                   #")
print("################################################################################")
print()
print("##########    Welcome to Hangman!")
print("#        |    You will be guessing a hidden word. You have a total of 6 attempts.")
print("#        |    To make a guess, enter a letter or try to guess the entire word.")
print("#        |    If the letter or word is correct, it will be revealed in its ")
print("#        ¿    corresponding position(s). You can also take a risk by guessing.")
print("#")
print("#             When guessing a letter, you should choose the position ")
print("#             of a dash to enter the letter.")
print("#")
print("#             Remember, if your attempts run out before you guess the word,")
print("=========     you lose the game.")
print("\n\n")
print("Let's begin! Enter a letter or the full word to start guessing.\n")

rand_select.select()
